export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_GROUP_SUCCESS = "GET_GROUP_SUCCESS";

export const ADD_CHILD_SUCCESS = "ADD_CHILD_SUCCESS";
export const GET_CHILDS = "GET_CHILDS";
export const LOADING_CHILDS = "LOADING_CHILDS";

export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const LOADING_POSTS = "LOADING_POSTS";
