export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOADING_AUTH = 'LOADING_AUTH';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GROUP_LOADING = 'GROUP_LOADING';
export const GROUP_ERROR = 'GROUP_ERROR';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const ADD_NEW_GROUP = 'ADD_NEW_GROUP';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const GET_TEACHER_GROUPS = 'GET_TEACHER_GROUPS';
export const SET_NEW_ASSIGNMENT = 'SET_NEW_ASSIGNMENT';
export const SET_NEW_TASK = 'SET_NEW_TASK';

export const ADD_CHILD_SUCCESS = 'ADD_CHILD_SUCCESS';
export const GET_CHILDS = 'GET_CHILDS';
export const LOADING_CHILDS = 'LOADING_CHILDS';
export const UPDATE_CHILD = 'UPDATE_CHILD';
export const DELETE_CHILD = 'DELETE_CHILD';
export const SET_ACTUAL_CHILD = 'SET_ACTUAL_CHILD';

export const POSTS_ERROR = 'POSTS_ERROR';
export const SET_NEW_POST = 'SET_NEW_POST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const LOADING_POSTS = 'LOADING_POSTS';

export const SENDING_TASK = 'SENDING_TASK';
export const SEND_TASK_SUCCESS = 'SEND_TASK_SUCCESS';

export const HOMEWORK_LOADING = 'HOMEWORK_LOADING';
export const HOMEWORK_ERROR = 'HOMEWORK_ERROR';
export const HOMEWORK_MESSAGE = 'HOMEWORK_MESSAGE';
export const GET_HOMEWORK_SUCCESS = 'GET_HOMEWORK_SUCCESS';
export const GET_STUDENT_HOMEWORK_SUCCESS = 'GET_STUDENT_HOMEWORK_SUCCESS';
export const UPDATED_HOMEWORK_SUCCESS = 'UPDATED_HOMEWORK_SUCCESS';
